### ISSUE TITLE
Reportlab Version 2.1+ is needed!

### ISSUE THREAD

**Issue by fehead** [hojel/epubia#8]
좋은 프로그램을 만들어 주셔서 감사합니다^^
잘 돌아 갑니다.
처음에 이 프로그램을 윈도우에서 돌렸을때 [TOC]가 안먹어서
리눅스에서 설치하고는 로그 확인하고 어떻게 어떻게 되어서 잘 되었습니다.
(윈도우에서 로그창이라도 띄워줬으면 하는 바람이^^)

또 윈도우에서는 pdf 까지 잘 나왔는데 
리눅스에서는 아래와 같은 로그가 나와서 pdf는 굳이 필요성을 못 느껴서 그냥 포기했습니다..
최고의 프로그램입니다^^//

```
****************************************************
IMPORT ERROR!
Reportlab Version 2.1+ is needed!
****************************************************

The following Python packages are required for PISA:
- Reportlab Toolkit >= 2.2 <http://www.reportlab.org/>
- HTML5lib >= 0.11.1 <http://code.google.com/p/html5lib/>

Optional packages:
- pyPDF <http://pybrary.net/pyPdf/>
- PIL <http://www.pythonware.com/products/pil/>

No handlers could be found for logger "sx.pisa3"
Traceback (most recent call last):
  File "/home/fehead/git/epubia/gui.py", line 300, in runConvert
    from markdown2pdf import markdown2pdf
  File "/home/fehead/git/epubia/markdown2pdf.py", line 3, in <module>
    import ho.pisa as pisa
  File "/usr/lib/pymodules/python2.7/ho/pisa/__init__.py", line 16, in <module>
    from sx.pisa3.pisa import *
  File "/usr/lib/pymodules/python2.7/sx/pisa3/__init__.py", line 31, in <module>
    from pisa import *
  File "/usr/lib/pymodules/python2.7/sx/pisa3/pisa.py", line 21, in <module>
    from pisa_document import *
  File "/usr/lib/pymodules/python2.7/sx/pisa3/pisa_document.py", line 11, in <module>
    from pisa_context import pisaContext
  File "/usr/lib/pymodules/python2.7/sx/pisa3/pisa_context.py", line 11, in <module>
    from pisa_util import *
  File "/usr/lib/pymodules/python2.7/sx/pisa3/pisa_util.py", line 44, in <module>
    raise ImportError("Reportlab Version 2.1+ is needed!")
ImportError: Reportlab Version 2.1+ is needed!
```

**Comment by hojel** [comment]
PDF는 만들어놓고 저도 까먹고 있는 기능입니다. 잘 포기하셨어요.
